/*
 This model class is reponsible for the logic of the converter. It performs the
 conversion calculations for display on the views and also writes the converted
 value to a file.
 
 @author David Pyle 041110777
 @version 1.0
 @since 4/4/2016
  
 Methods:
    - int getUnitCategory()
    - void setUnitCategory(int whichUnits)   
    - void setUnitFromIndex(int fromIndex)
    - int getUnitFromIndex()
    - void setUnitToIndex(int toIndex)
    - int getUnitToIndex()
    - void setToBox(boolean val)
    - String formatValue(double value)
    - void doConversion(double valueToConvert)
    - String txtFileHeaders()
    - String writeToFile(String content, String path)
    - String convertFile(String importPath, String savePath)
    - double getConversionResult()
    - String[] getConversionItems()
    - String[] getUnitMenuItems()

 Classes this class requires    
    java.awt.Toolkit;
    java.awt.event.ActionListener;
    java.awt.event.ItemListener;
    java.awt.event.KeyAdapter;
    java.math.BigDecimal;
    java.text.DecimalFormat;
    javax.swing.KeyStroke;
 */

package myconverter;

import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.KeyStroke;

/**
 *
 * @author davidpyle
 */
public class JConverterView extends javax.swing.JFrame {

    /**
     * Creates new form JConverterView
     */
    public JConverterView() {
        
        initComponents();
        menuImport.setAccelerator(KeyStroke.getKeyStroke('I', Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()));
        menuExit.setAccelerator(KeyStroke.getKeyStroke('Q', Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtUnitFrom = new javax.swing.JTextField();
        lblEqualsSign = new javax.swing.JLabel();
        txtUnitTo = new javax.swing.JTextField();
        cmbUnitTo = new javax.swing.JComboBox();
        cmbUnitFrom = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        cmbUnitCategory = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuImport = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JConverter");
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Unit Conversion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        txtUnitFrom.setColumns(10);
        txtUnitFrom.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblEqualsSign.setText("=");

        txtUnitTo.setColumns(10);
        txtUnitTo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUnitFrom)
                    .addComponent(cmbUnitFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lblEqualsSign)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUnitTo)
                    .addComponent(cmbUnitTo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUnitFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUnitTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEqualsSign)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUnitFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUnitTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Unit Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N

        cmbUnitCategory.setMinimumSize(new java.awt.Dimension(160, 27));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(cmbUnitCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cmbUnitCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.BorderLayout());

        lblMessage.setForeground(new java.awt.Color(255, 51, 51));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("File");

        menuImport.setText("Import");
        jMenu1.add(menuImport);

        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String formatValue(double value) {

        int decimalPlaces = 5;
        BigDecimal bd = new BigDecimal(value);
        bd = bd.setScale(decimalPlaces, BigDecimal.ROUND_HALF_UP);

        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(5);
        df.setMinimumFractionDigits(0);
        df.setGroupingUsed(false);

        String result = df.format(bd);

        return result;
    }

    public double getFromValue() {
        if (txtUnitFrom.getText().isEmpty()) {
            return 0;
        } else {                    
            return Double.parseDouble(txtUnitFrom.getText());
        }
    }

    public void setFromValue(double convertedValue) {
        //System.out.println("Setting from value in textfield: " + convertedValue);
        txtUnitFrom.setText(formatValue(convertedValue));
    }

    public double getToValue() {
        if (txtUnitTo.getText().isEmpty()) {
            return 0;
        } else {                    
            return Double.parseDouble(txtUnitTo.getText());
        }
    }

    public void setToValue(double convertedValue) {
        //System.out.println("Setting to value in textfield: " + convertedValue);
        txtUnitTo.setText(formatValue(convertedValue));
    }

    public void setFromCategory(int index) {
        cmbUnitFrom.setSelectedIndex(index);
    }

    public void setToCategory(int index) {
        cmbUnitTo.setSelectedIndex(index);
    }

    public void setUnitCategory(int unitCat) {
        cmbUnitCategory.setSelectedIndex(unitCat);
    }

    public int getUnitCategory() {
        return cmbUnitCategory.getSelectedIndex();
    }

    public void setUnitFromItems(String[] unitFromCat) {

        cmbUnitFrom.removeAllItems();

        for (String conversion : unitFromCat) {
            cmbUnitFrom.addItem(conversion);
        }
    }

    public void setUnitToItems(String[] unitToCat) {

        cmbUnitTo.removeAllItems();

        for (String conversion : unitToCat) {
            cmbUnitTo.addItem(conversion);
        }
    }

    public void setUnitCat(String[] unitCat) {

        cmbUnitCategory.removeAllItems();

        for (String conversion : unitCat) {
            cmbUnitCategory.addItem(conversion);
        }
    }

    void addInputFromListener(KeyAdapter listenInputFrom) {
        txtUnitFrom.addKeyListener(listenInputFrom);
    }

    void addInputToListener(KeyAdapter listenInputTo) {
        txtUnitTo.addKeyListener(listenInputTo);
    }

    void addUnitCatListener(ItemListener listenUnitCat) {
        cmbUnitCategory.addItemListener(listenUnitCat);
    }

    void addUnitFromListener(ItemListener listenUnitFrom) {
        cmbUnitFrom.addItemListener(listenUnitFrom);
    }

    void addUnitToListener(ItemListener listenUnitTo) {
        cmbUnitTo.addItemListener(listenUnitTo);
    }

    void addExitListener(ActionListener listenForExit) {
        menuExit.addActionListener(listenForExit);
    }

    void addImportMenuListener(ActionListener listenForImport) {
        menuImport.addActionListener(listenForImport);
    }

    void displayMsg(String msg, String msgType) {
        switch (msgType) {
            case "error":
                //JOptionPane.showMessageDialog(this, msg, msgTitle, JOptionPane.ERROR_MESSAGE);
		lblMessage.setText("Error: " + msg);
                break;
            case "warning":
                //JOptionPane.showMessageDialog(this, msg, msgTitle, JOptionPane.WARNING_MESSAGE);
		lblMessage.setText("Warning: " + msg);
                break;
            default:
                //JOptionPane.showMessageDialog(this, msg);
		lblMessage.setText(msg);

        }
	
    }
    
    void clearMsg() {
	lblMessage.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbUnitCategory;
    private javax.swing.JComboBox cmbUnitFrom;
    private javax.swing.JComboBox cmbUnitTo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEqualsSign;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuImport;
    private javax.swing.JTextField txtUnitFrom;
    private javax.swing.JTextField txtUnitTo;
    // End of variables declaration//GEN-END:variables
}
